// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EdFi.Ods.WebService.Tests.Profiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Profile definitions can include and exclude specific properties on child collecti" +
        "ons")]
    [NUnit.Framework.CategoryAttribute("API")]
    [NUnit.Framework.CategoryAttribute("SDK")]
    public partial class ProfileDefinitionsCanIncludeAndExcludeSpecificPropertiesOnChildCollectionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Profile definitions can include and exclude specific properties on child collections.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Profile definitions can include and exclude specific properties on child collecti" +
                    "ons", "", ProgrammingLanguage.CSharp, new string[] {
                        "API",
                        "SDK"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Read content type only includes certain properties from a child collection")]
        [NUnit.Framework.TestCaseAttribute("the SDK", null)]
        [NUnit.Framework.TestCaseAttribute("raw JSON", null)]
        public virtual void TheReadContentTypeOnlyIncludesCertainPropertiesFromAChildCollection(string callMechanism, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Read content type only includes certain properties from a child collection", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
    testRunner.Given("the caller is using the \"Test-Profile-AssessmentFamily-Resource-Child-Collection-" +
                    "IncludeOnly\" profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
    testRunner.When(string.Format("a GET (by id) request is submitted using {0} to assessmentFamilies with an accept" +
                        " header content type of the appropriate value for the profile in use", callMechanism), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
    testRunner.Then("the response model\'s identificationCodes collection items should contain the cont" +
                    "extual primary key properties of [assessmentIdentificationSystemDescriptor]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 8
    testRunner.And("the response model\'s identificationCodes collection items should contain the expl" +
                    "icitly included properties of [identificationCode]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
    testRunner.And("the number of properties on the response model\'s base class identificationCodes c" +
                    "ollection items should reflect the number of included properties plus the contex" +
                    "tual primary key properties", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Read content type only excludes certain properties from a child collection")]
        [NUnit.Framework.TestCaseAttribute("the SDK", null)]
        [NUnit.Framework.TestCaseAttribute("raw JSON", null)]
        public virtual void TheReadContentTypeOnlyExcludesCertainPropertiesFromAChildCollection(string callMechanism, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Read content type only excludes certain properties from a child collection", exampleTags);
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
    testRunner.Given("the caller is using the \"Test-Profile-AssessmentFamily-Resource-Child-Collection-" +
                    "ExcludeOnly\" profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
    testRunner.When(string.Format("a GET (by id) request is submitted using {0} to assessmentFamilies with an accept" +
                        " header content type of the appropriate value for the profile in use", callMechanism), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
    testRunner.Then("the response model\'s identificationCodes collection items should contain the cont" +
                    "extual primary key properties of [assessmentIdentificationSystemDescriptor]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 20
    testRunner.And("the response model\'s identificationCodes collection items should not contain the " +
                    "explicitly excluded properties of [identificationCode]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
    testRunner.And("the number of properties on the response model\'s base class identificationCodes c" +
                    "ollection items should reflect the number of properties on the full AssessmentFa" +
                    "milyIdentificationCode resource model less the explicitly excluded ones", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Write content type only includes certain properties from a child collection")]
        [NUnit.Framework.TestCaseAttribute("the SDK", null)]
        [NUnit.Framework.TestCaseAttribute("raw JSON", null)]
        public virtual void TheWriteContentTypeOnlyIncludesCertainPropertiesFromAChildCollection(string callMechanism, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Write content type only includes certain properties from a child collection", exampleTags);
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
    testRunner.Given("the caller is using the \"Test-Profile-AssessmentFamily-Resource-Child-Collection-" +
                    "IncludeOnly\" profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
    testRunner.When(string.Format("a PUT request with a completely updated resource with preserved child collections" +
                        " is submitted using {0} to assessmentFamilies with a request body content type o" +
                        "f the appropriate value for the profile in use", callMechanism), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
    testRunner.Then("the only values changed on the entity model\'s AssessmentFamilyIdentificationCodes" +
                    " collection items should be the explicitly included properties of AssigningOrgan" +
                    "izationIdentificationCode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Write content type only excludes certain properties from a child collection")]
        [NUnit.Framework.TestCaseAttribute("the SDK", null)]
        [NUnit.Framework.TestCaseAttribute("raw JSON", null)]
        public virtual void TheWriteContentTypeOnlyExcludesCertainPropertiesFromAChildCollection(string callMechanism, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Write content type only excludes certain properties from a child collection", exampleTags);
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
    testRunner.Given("the caller is using the \"Test-Profile-AssessmentFamily-Resource-Child-Collection-" +
                    "ExcludeOnly\" profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 40
    testRunner.When(string.Format("a PUT request with a completely updated resource with preserved child collections" +
                        " is submitted using {0} to assessmentFamilies with a request body content type o" +
                        "f the appropriate value for the profile in use", callMechanism), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
    testRunner.Then(@"the only values not changed on the entity model's AssessmentFamilyIdentificationCodes collection items should be the contextual primary key values of [AssessmentIdentificationSystemDescriptor, AssessmentIdentificationSystemDescriptorId], and the explicitly excluded properties of [AssigningOrganizationIdentificationCode]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
