// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EdFi.Ods.WebService.Tests.Profiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Profile definitions can include all members of a resource or collection")]
    [NUnit.Framework.CategoryAttribute("API")]
    [NUnit.Framework.CategoryAttribute("SDK")]
    public partial class ProfileDefinitionsCanIncludeAllMembersOfAResourceOrCollectionFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Profile definitions can include all members of a resource or collection.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Profile definitions can include all members of a resource or collection", "", ProgrammingLanguage.CSharp, new string[] {
                        "API",
                        "SDK"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Read content type includes all properties of a resource")]
        [NUnit.Framework.TestCaseAttribute("the SDK", null)]
        [NUnit.Framework.TestCaseAttribute("raw JSON", null)]
        public virtual void TheReadContentTypeIncludesAllPropertiesOfAResource(string callMechanism, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Read content type includes all properties of a resource", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
    testRunner.Given("the caller is using the \"Test-Profile-Resource-IncludeAll\" profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
    testRunner.When(string.Format("a GET (by id) request is submitted using {0} to schools with an accept header con" +
                        "tent type of the appropriate value for the profile in use", callMechanism), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
    testRunner.Then("the response model should contain all of the resource model\'s properties", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Write content type includes all properties of a resource")]
        [NUnit.Framework.TestCaseAttribute("the SDK", null)]
        [NUnit.Framework.TestCaseAttribute("raw JSON", null)]
        public virtual void TheWriteContentTypeIncludesAllPropertiesOfAResource(string callMechanism, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Write content type includes all properties of a resource", exampleTags);
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
    testRunner.Given("the caller is using the \"Test-Profile-Resource-IncludeAll\" profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
    testRunner.When(string.Format("a PUT request with a completely updated resource is submitted using {0} to school" +
                        "s with a request body content type of the appropriate value for the profile in u" +
                        "se", callMechanism), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
    testRunner.Then("the persisted entity model should have unmodified primary key values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
    testRunner.And("every non-primary key value on the entity should be changed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Read content type includes all properties of a child collection")]
        [NUnit.Framework.TestCaseAttribute("the SDK", null)]
        [NUnit.Framework.TestCaseAttribute("raw JSON", null)]
        public virtual void TheReadContentTypeIncludesAllPropertiesOfAChildCollection(string callMechanism, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Read content type includes all properties of a child collection", exampleTags);
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
    testRunner.Given("the caller is using the \"Test-Profile-Resource-Child-Collection-IncludeAll\" profi" +
                    "le", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 27
    testRunner.When(string.Format("a GET (by id) request is submitted using {0} to schools with an accept header con" +
                        "tent type of the appropriate value for the profile in use", callMechanism), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
    testRunner.Then("the number of properties on the response model\'s addresses collection items shoul" +
                    "d reflect the number of properties on the full EducationOrganizationAddress reso" +
                    "urce model", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Write content type includes all properties of a child collection")]
        [NUnit.Framework.TestCaseAttribute("the SDK", null)]
        [NUnit.Framework.TestCaseAttribute("raw JSON", null)]
        public virtual void TheWriteContentTypeIncludesAllPropertiesOfAChildCollection(string callMechanism, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Write content type includes all properties of a child collection", exampleTags);
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
    testRunner.Given("the caller is using the \"Test-Profile-Resource-Child-Collection-IncludeAll\" profi" +
                    "le", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
    testRunner.When(string.Format("a PUT request with a completely updated resource with preserved child collections" +
                        " is submitted using {0} to schools with a request body content type of the appro" +
                        "priate value for the profile in use", callMechanism), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
    testRunner.Then("the only values not changed on the entity model\'s EducationOrganizationInternatio" +
                    "nalAddresses collection items should be the contextual primary key values of [Ad" +
                    "dressType, AddressTypeId]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
