// <auto-generated />
namespace EdFi.Ods.Admin.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddClaimSetNameToApplication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClaimSetNameToApplication));
        
        string IMigrationMetadata.Id
        {
            get { return "201412191459507_AddClaimSetNameToApplication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
