// <auto-generated />
namespace EdFi.Ods.Api.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddStackTrace : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStackTrace));
        
        string IMigrationMetadata.Id
        {
            get { return "201411131927126_AddStackTrace"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
